# we need a copy of docker running
# build out dockerfile.dev
# tell travis how to rn test suite
#  tell travis how to deploy to aws

sudo: required # need root permissions
services:
  - docker

before_install:
  - docker build -t gaowgr/docker-react -f Dockerfile.dev .

script:
  - docker run gaowgr/docker-react npm run test -- --coverage

deploy:
  provider: elasticbeanstalk
  region: 'us-east-1'
  app: 'docker-react'
  env: 'DockerReact-env'
  bucket_name: 'elasticbeanstalk-us-east-1-752455431707'
  bucket_path: 'docker-react'
  on: #  only deploy when code pushed to master
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key:
    secure: '$AWS_SECRET_KEY'
